[package]
authors = [
  "Toshiaki Takada <toshi@reze.rs>",
  "Valentin Kivachuk Burda <foss@vk496.es>",
]
edition = "2021"
name = "notif_send"
version = "0.3.0"

[dependencies]
sysrepo = {path = "../.."}
